<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="ClosedXML" Version="0.104.2" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="EFCore.NamingConventions" Version="8.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.29" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.29" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.29" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.29" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.7.6" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

</Project>
