CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE costs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        campaign_id integer,
        type character varying(20) NOT NULL,
        provider character varying(100) NOT NULL,
        reference_id character varying(200),
        amount numeric(14,2) NOT NULL,
        currency character varying(3) NOT NULL,
        date timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_costs PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE import_batches (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        file_name character varying(300) NOT NULL,
        source_id integer,
        total_records integer NOT NULL,
        valid_records integer NOT NULL,
        duplicate_records integer NOT NULL,
        invalid_records integer NOT NULL,
        suppressed_records integer NOT NULL,
        status character varying(20) NOT NULL,
        created_by integer,
        created_at timestamp with time zone NOT NULL,
        completed_at timestamp with time zone,
        CONSTRAINT pk_import_batches PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE message_templates (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        name character varying(150) NOT NULL,
        content text NOT NULL,
        channel character varying(20) NOT NULL,
        version integer NOT NULL,
        is_active boolean NOT NULL,
        created_by integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_message_templates PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE organizations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(200) NOT NULL,
        legal_name character varying(200),
        tax_id character varying(20),
        email character varying(200),
        phone character varying(30),
        address character varying(300),
        city character varying(120),
        province character varying(120),
        country character varying(120),
        timezone character varying(60) NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_organizations PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE prospects (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        business_name character varying(200) NOT NULL,
        contact_name character varying(200),
        category character varying(30) NOT NULL,
        business_size character varying(20) NOT NULL,
        recurrence_potential character varying(20) NOT NULL,
        distance_category character varying(20) NOT NULL,
        data_quality character varying(5) NOT NULL,
        address character varying(300),
        city character varying(120),
        province character varying(120),
        country character varying(120),
        postal_code character varying(20),
        latitude double precision,
        longitude double precision,
        website character varying(300),
        commercial_score integer,
        operational_priority character varying(20),
        status character varying(30) NOT NULL,
        is_deleted boolean NOT NULL,
        deleted_at timestamp with time zone,
        last_contacted_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_prospects PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE roles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(30) NOT NULL,
        CONSTRAINT pk_roles PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE suppressions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        contact character varying(200) NOT NULL,
        contact_type character varying(20) NOT NULL,
        reason character varying(30) NOT NULL,
        source character varying(200),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_suppressions PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE tags (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        name character varying(60) NOT NULL,
        color character varying(20),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_tags PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE import_batch_records (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        import_batch_id integer NOT NULL,
        row_number integer NOT NULL,
        raw_data jsonb NOT NULL,
        normalized_data jsonb,
        status character varying(20) NOT NULL,
        error_message text,
        prospect_id integer,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_import_batch_records PRIMARY KEY (id),
        CONSTRAINT fk_import_batch_records_import_batches_import_batch_id FOREIGN KEY (import_batch_id) REFERENCES import_batches (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE campaigns (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        name character varying(200) NOT NULL,
        description character varying(1000),
        status character varying(20) NOT NULL,
        channel character varying(20) NOT NULL,
        message_template_id integer NOT NULL,
        max_messages integer NOT NULL,
        messages_per_minute integer NOT NULL,
        messages_per_hour integer NOT NULL,
        messages_per_day integer NOT NULL,
        start_date timestamp with time zone,
        end_date timestamp with time zone,
        created_by integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_campaigns PRIMARY KEY (id),
        CONSTRAINT fk_campaigns_message_templates_message_template_id FOREIGN KEY (message_template_id) REFERENCES message_templates (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE organization_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        key character varying(100) NOT NULL,
        value text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_organization_settings PRIMARY KEY (id),
        CONSTRAINT fk_organization_settings_organizations_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        first_name character varying(120) NOT NULL,
        last_name character varying(120) NOT NULL,
        email character varying(200) NOT NULL,
        phone character varying(30),
        password_hash character varying(500) NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id),
        CONSTRAINT fk_users_organizations_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE leads (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        prospect_id integer NOT NULL,
        campaign_id integer,
        assigned_to_user_id integer,
        status character varying(20) NOT NULL,
        priority character varying(10) NOT NULL,
        lost_reason character varying(30),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        first_response_at timestamp with time zone,
        last_activity_at timestamp with time zone,
        closed_at timestamp with time zone,
        CONSTRAINT pk_leads PRIMARY KEY (id),
        CONSTRAINT fk_leads_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE message_responses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        prospect_id integer NOT NULL,
        campaign_id integer,
        message_id integer,
        content text NOT NULL,
        received_at timestamp with time zone NOT NULL,
        classification character varying(20) NOT NULL,
        confidence numeric(4,2) NOT NULL,
        ai_model character varying(100),
        ai_prompt_version character varying(50),
        external_inbound_id character varying(200),
        processed_at timestamp with time zone,
        CONSTRAINT pk_message_responses PRIMARY KEY (id),
        CONSTRAINT fk_message_responses_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE messages (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        prospect_id integer NOT NULL,
        campaign_id integer,
        campaign_recipient_id integer,
        template_id integer,
        channel character varying(20) NOT NULL,
        provider character varying(50) NOT NULL,
        content text NOT NULL,
        external_message_id character varying(200),
        status character varying(20) NOT NULL,
        sent_at timestamp with time zone,
        delivered_at timestamp with time zone,
        read_at timestamp with time zone,
        failed_at timestamp with time zone,
        cost numeric(14,2),
        currency character varying(3),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_messages PRIMARY KEY (id),
        CONSTRAINT fk_messages_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE prospect_contacts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        prospect_id integer NOT NULL,
        channel character varying(20) NOT NULL,
        value character varying(200) NOT NULL,
        is_primary boolean NOT NULL,
        is_verified boolean NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_prospect_contacts PRIMARY KEY (id),
        CONSTRAINT fk_prospect_contacts_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE prospect_sources (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        prospect_id integer NOT NULL,
        source_type character varying(30) NOT NULL,
        external_id character varying(200),
        source_url character varying(500),
        collected_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_prospect_sources PRIMARY KEY (id),
        CONSTRAINT fk_prospect_sources_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE prospect_tags (
        prospect_id integer NOT NULL,
        tag_id integer NOT NULL,
        CONSTRAINT pk_prospect_tags PRIMARY KEY (prospect_id, tag_id),
        CONSTRAINT fk_prospect_tags_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE CASCADE,
        CONSTRAINT fk_prospect_tags_tags_tag_id FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE campaign_recipients (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        campaign_id integer NOT NULL,
        prospect_id integer NOT NULL,
        status character varying(20) NOT NULL,
        attempts integer NOT NULL,
        last_attempt_at timestamp with time zone,
        first_message_id integer,
        last_message_id integer,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_campaign_recipients PRIMARY KEY (id),
        CONSTRAINT fk_campaign_recipients_campaigns_campaign_id FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE,
        CONSTRAINT fk_campaign_recipients_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE refresh_tokens (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        token_hash character varying(128) NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
        CONSTRAINT fk_refresh_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE user_roles (
        user_id integer NOT NULL,
        role_id integer NOT NULL,
        CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
        CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT,
        CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE follow_ups (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        lead_id integer NOT NULL,
        user_id integer NOT NULL,
        scheduled_at timestamp with time zone NOT NULL,
        status character varying(20) NOT NULL,
        notes character varying(1000),
        completed_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_follow_ups PRIMARY KEY (id),
        CONSTRAINT fk_follow_ups_leads_lead_id FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE lead_activities (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        lead_id integer NOT NULL,
        user_id integer NOT NULL,
        type character varying(20) NOT NULL,
        description text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_lead_activities PRIMARY KEY (id),
        CONSTRAINT fk_lead_activities_leads_lead_id FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE TABLE sales (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        lead_id integer NOT NULL,
        campaign_id integer,
        prospect_id integer NOT NULL,
        seller_id integer NOT NULL,
        amount numeric(14,2) NOT NULL,
        currency character varying(3) NOT NULL,
        margin numeric(14,2),
        product_category character varying(150),
        status character varying(20) NOT NULL,
        date timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_sales PRIMARY KEY (id),
        CONSTRAINT fk_sales_leads_lead_id FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE RESTRICT,
        CONSTRAINT fk_sales_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    INSERT INTO roles (id, name)
    VALUES (1, 'OWNER');
    INSERT INTO roles (id, name)
    VALUES (2, 'ADMIN');
    INSERT INTO roles (id, name)
    VALUES (3, 'MANAGER');
    INSERT INTO roles (id, name)
    VALUES (4, 'SELLER');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_campaign_recipients_campaign_id_prospect_id ON campaign_recipients (campaign_id, prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_campaign_recipients_prospect_id ON campaign_recipients (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_campaigns_message_template_id ON campaigns (message_template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_campaigns_organization_id_status ON campaigns (organization_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_costs_campaign_id ON costs (campaign_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_costs_organization_id ON costs (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_follow_ups_lead_id ON follow_ups (lead_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_follow_ups_scheduled_at ON follow_ups (scheduled_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_import_batch_records_import_batch_id ON import_batch_records (import_batch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_import_batches_organization_id ON import_batches (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_lead_activities_lead_id ON lead_activities (lead_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_leads_organization_id_assigned_to_user_id ON leads (organization_id, assigned_to_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_leads_organization_id_status ON leads (organization_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_leads_prospect_id ON leads (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_message_responses_campaign_id ON message_responses (campaign_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_message_responses_organization_id_external_inbound_id ON message_responses (organization_id, external_inbound_id) WHERE external_inbound_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_message_responses_organization_id_prospect_id ON message_responses (organization_id, prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_message_responses_prospect_id ON message_responses (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_message_templates_organization_id_name ON message_templates (organization_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_messages_campaign_id ON messages (campaign_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_messages_external_message_id ON messages (external_message_id) WHERE external_message_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_messages_organization_id_prospect_id ON messages (organization_id, prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_messages_prospect_id ON messages (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_organization_settings_organization_id_key ON organization_settings (organization_id, key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_organizations_tax_id ON organizations (tax_id) WHERE tax_id IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_prospect_contacts_organization_id_channel_value ON prospect_contacts (organization_id, channel, value);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospect_contacts_prospect_id ON prospect_contacts (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospect_sources_prospect_id ON prospect_sources (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospect_sources_source_type_external_id ON prospect_sources (source_type, external_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospect_tags_tag_id ON prospect_tags (tag_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospects_organization_id ON prospects (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospects_organization_id_category ON prospects (organization_id, category);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospects_organization_id_city ON prospects (organization_id, city);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospects_organization_id_operational_priority ON prospects (organization_id, operational_priority);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_prospects_organization_id_status ON prospects (organization_id, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_roles_name ON roles (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_sales_campaign_id ON sales (campaign_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_sales_lead_id ON sales (lead_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_sales_organization_id ON sales (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_sales_prospect_id ON sales (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_sales_seller_id ON sales (seller_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_suppressions_organization_id_contact ON suppressions (organization_id, contact);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_tags_organization_id_name ON tags (organization_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE INDEX ix_users_organization_id ON users (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_users_organization_id_email ON users (organization_id, email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('roles', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM roles) + 1,
            nextval(pg_get_serial_sequence('roles', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260727231918_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260727231918_InitialCreate', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260728004438_AddImportBatchSourceType') THEN
    ALTER TABLE import_batches ADD source_type character varying(30) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260728004438_AddImportBatchSourceType') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260728004438_AddImportBatchSourceType', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260728233511_AddCatalogTemplateFlag') THEN
    ALTER TABLE message_templates ADD is_catalog_template boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260728233511_AddCatalogTemplateFlag') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260728233511_AddCatalogTemplateFlag', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260730233804_AddMessageFailureReason') THEN
    ALTER TABLE messages ADD failure_reason character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260730233804_AddMessageFailureReason') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260730233804_AddMessageFailureReason', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260803192231_AddUserArea') THEN
    ALTER TABLE users ADD area character varying(20) NOT NULL DEFAULT 'Unassigned';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260803192231_AddUserArea') THEN
    CREATE INDEX ix_users_organization_id_area ON users (organization_id, area);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260803192231_AddUserArea') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260803192231_AddUserArea', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260803192852_AddMessageResponseButtonPayload') THEN
    ALTER TABLE message_responses ADD button_payload character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260803192852_AddMessageResponseButtonPayload') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260803192852_AddMessageResponseButtonPayload', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805052353_AddUserTelegramChatId') THEN
    ALTER TABLE users ADD telegram_chat_id character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805052353_AddUserTelegramChatId') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260805052353_AddUserTelegramChatId', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805054549_AddUserTelegramLinkCode') THEN
    ALTER TABLE users ADD telegram_link_code character varying(64);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805054549_AddUserTelegramLinkCode') THEN
    ALTER TABLE users ADD telegram_link_code_expires_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805054549_AddUserTelegramLinkCode') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260805054549_AddUserTelegramLinkCode', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805105711_AddScheduledProspectAutomation') THEN
    CREATE TABLE scheduled_prospect_automations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        created_by_user_id integer NOT NULL,
        search_criteria_json jsonb NOT NULL,
        campaign_id integer NOT NULL,
        scheduled_at timestamp with time zone NOT NULL,
        status character varying(20) NOT NULL,
        run_at timestamp with time zone,
        result_summary character varying(2000),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_scheduled_prospect_automations PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805105711_AddScheduledProspectAutomation') THEN
    CREATE INDEX ix_scheduled_prospect_automations_organization_id_status_sched ON scheduled_prospect_automations (organization_id, status, scheduled_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260805105711_AddScheduledProspectAutomation') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260805105711_AddScheduledProspectAutomation', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807234453_AddScheduledMessage') THEN
    CREATE TABLE scheduled_messages (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        organization_id integer NOT NULL,
        created_by_user_id integer NOT NULL,
        prospect_id integer NOT NULL,
        message_template_id integer NOT NULL,
        scheduled_at timestamp with time zone NOT NULL,
        status character varying(20) NOT NULL,
        run_at timestamp with time zone,
        message_id integer,
        failure_reason character varying(500),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_scheduled_messages PRIMARY KEY (id),
        CONSTRAINT fk_scheduled_messages_message_templates_message_template_id FOREIGN KEY (message_template_id) REFERENCES message_templates (id) ON DELETE RESTRICT,
        CONSTRAINT fk_scheduled_messages_prospects_prospect_id FOREIGN KEY (prospect_id) REFERENCES prospects (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807234453_AddScheduledMessage') THEN
    CREATE INDEX ix_scheduled_messages_message_template_id ON scheduled_messages (message_template_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807234453_AddScheduledMessage') THEN
    CREATE INDEX ix_scheduled_messages_organization_id_status_scheduled_at ON scheduled_messages (organization_id, status, scheduled_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807234453_AddScheduledMessage') THEN
    CREATE INDEX ix_scheduled_messages_prospect_id ON scheduled_messages (prospect_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260807234453_AddScheduledMessage') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260807234453_AddScheduledMessage', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260809145215_AddAutoReplyDetection') THEN
    ALTER TABLE scheduled_messages ALTER COLUMN created_by_user_id DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260809145215_AddAutoReplyDetection') THEN
    ALTER TABLE scheduled_messages ADD source character varying(30) NOT NULL DEFAULT 'Manual';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260809145215_AddAutoReplyDetection') THEN
    ALTER TABLE prospects ADD auto_reply_attempts integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260809145215_AddAutoReplyDetection') THEN
    ALTER TABLE message_templates ADD is_follow_up_template boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260809145215_AddAutoReplyDetection') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260809145215_AddAutoReplyDetection', '8.0.29');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260812125803_AddProspectLastViewedAt') THEN
    ALTER TABLE prospects ADD last_viewed_at timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20260812125803_AddProspectLastViewedAt') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20260812125803_AddProspectLastViewedAt', '8.0.29');
    END IF;
END $EF$;
COMMIT;

