<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Hunter.Domain\Hunter.Domain.csproj" />
    <ProjectReference Include="..\Hunter.Shared\Hunter.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
