// <auto-generated />
using System;
using Hunter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hunter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HunterDbContext))]
    [Migration("20260803192852_AddMessageResponseButtonPayload")]
    partial class AddMessageResponseButtonPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hunter.Domain.Campaigning.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("MaxMessages")
                        .HasColumnType("integer")
                        .HasColumnName("max_messages");

                    b.Property<int>("MessageTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("message_template_id");

                    b.Property<int>("MessagesPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("messages_per_day");

                    b.Property<int>("MessagesPerHour")
                        .HasColumnType("integer")
                        .HasColumnName("messages_per_hour");

                    b.Property<int>("MessagesPerMinute")
                        .HasColumnType("integer")
                        .HasColumnName("messages_per_minute");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.HasIndex("MessageTemplateId")
                        .HasDatabaseName("ix_campaigns_message_template_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_campaigns_organization_id_status");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.CampaignRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("FirstMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("first_message_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<int?>("LastMessageId")
                        .HasColumnType("integer")
                        .HasColumnName("last_message_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_campaign_recipients");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_campaign_recipients_prospect_id");

                    b.HasIndex("CampaignId", "ProspectId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_recipients_campaign_id_prospect_id");

                    b.ToTable("campaign_recipients", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<int?>("CampaignRecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_recipient_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_message_id");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_messages_campaign_id");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_messages_external_message_id")
                        .HasFilter("external_message_id IS NOT NULL");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_messages_prospect_id");

                    b.HasIndex("OrganizationId", "ProspectId")
                        .HasDatabaseName("ix_messages_organization_id_prospect_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.MessageResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_model");

                    b.Property<string>("AiPromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ai_prompt_version");

                    b.Property<string>("ButtonPayload")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("button_payload");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ExternalInboundId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_inbound_id");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_message_responses");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_message_responses_campaign_id");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_message_responses_prospect_id");

                    b.HasIndex("OrganizationId", "ExternalInboundId")
                        .IsUnique()
                        .HasDatabaseName("ix_message_responses_organization_id_external_inbound_id")
                        .HasFilter("external_inbound_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "ProspectId")
                        .HasDatabaseName("ix_message_responses_organization_id_prospect_id");

                    b.ToTable("message_responses", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.MessageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCatalogTemplate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_catalog_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_message_templates");

                    b.HasIndex("OrganizationId", "Name")
                        .HasDatabaseName("ix_message_templates_organization_id_name");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Compliance.Suppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_suppressions");

                    b.HasIndex("OrganizationId", "Contact")
                        .IsUnique()
                        .HasDatabaseName("ix_suppressions_organization_id_contact");

                    b.ToTable("suppressions", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Crm.FollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_follow_ups");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_follow_ups_lead_id");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_follow_ups_scheduled_at");

                    b.ToTable("follow_ups", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Crm.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FirstResponseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_response_at");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("LostReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("lost_reason");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("priority");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_leads_prospect_id");

                    b.HasIndex("OrganizationId", "AssignedToUserId")
                        .HasDatabaseName("ix_leads_organization_id_assigned_to_user_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_leads_organization_id_status");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Crm.LeadActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lead_activities");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_lead_activities_lead_id");

                    b.ToTable("lead_activities", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Finance.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_costs");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_costs_campaign_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_costs_organization_id");

                    b.ToTable("costs", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "OWNER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ADMIN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MANAGER"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SELLER"
                        });
                });

            modelBuilder.Entity("Hunter.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unassigned")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("last_name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.HasIndex("OrganizationId", "Area")
                        .HasDatabaseName("ix_users_organization_id_area");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_organization_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Organizations.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("province");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Organizations.OrganizationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_organization_settings");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_settings_organization_id_key");

                    b.ToTable("organization_settings", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<int>("DuplicateRecords")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_records");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<int>("InvalidRecords")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_records");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("SuppressedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("suppressed_records");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<int>("ValidRecords")
                        .HasColumnType("integer")
                        .HasColumnName("valid_records");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_import_batches_organization_id");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ImportBatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("NormalizedData")
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_data");

                    b.Property<int?>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_batch_records");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_import_batch_records_import_batch_id");

                    b.ToTable("import_batch_records", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.Prospect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_size");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<int?>("CommercialScore")
                        .HasColumnType("integer")
                        .HasColumnName("commercial_score");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("Country")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("data_quality");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DistanceCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("distance_category");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastContactedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_contacted_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("OperationalPriority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operational_priority");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("province");

                    b.Property<string>("RecurrencePotential")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurrence_potential");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_prospects");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_prospects_organization_id");

                    b.HasIndex("OrganizationId", "Category")
                        .HasDatabaseName("ix_prospects_organization_id_category");

                    b.HasIndex("OrganizationId", "City")
                        .HasDatabaseName("ix_prospects_organization_id_city");

                    b.HasIndex("OrganizationId", "OperationalPriority")
                        .HasDatabaseName("ix_prospects_organization_id_operational_priority");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_prospects_organization_id_status");

                    b.ToTable("prospects", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_prospect_contacts");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_prospect_contacts_prospect_id");

                    b.HasIndex("OrganizationId", "Channel", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_prospect_contacts_organization_id_channel_value");

                    b.ToTable("prospect_contacts", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.HasKey("Id")
                        .HasName("pk_prospect_sources");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_prospect_sources_prospect_id");

                    b.HasIndex("SourceType", "ExternalId")
                        .HasDatabaseName("ix_prospect_sources_source_type_external_id");

                    b.ToTable("prospect_sources", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectTag", b =>
                {
                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("ProspectId", "TagId")
                        .HasName("pk_prospect_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_prospect_tags_tag_id");

                    b.ToTable("prospect_tags", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_organization_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer")
                        .HasColumnName("lead_id");

                    b.Property<decimal?>("Margin")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("margin");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProductCategory")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_category");

                    b.Property<int>("ProspectId")
                        .HasColumnType("integer")
                        .HasColumnName("prospect_id");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_sales_campaign_id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_sales_lead_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sales_organization_id");

                    b.HasIndex("ProspectId")
                        .HasDatabaseName("ix_sales_prospect_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_sales_seller_id");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.Campaign", b =>
                {
                    b.HasOne("Hunter.Domain.Campaigning.MessageTemplate", "MessageTemplate")
                        .WithMany()
                        .HasForeignKey("MessageTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaigns_message_templates_message_template_id");

                    b.Navigation("MessageTemplate");
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.CampaignRecipient", b =>
                {
                    b.HasOne("Hunter.Domain.Campaigning.Campaign", "Campaign")
                        .WithMany("Recipients")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_recipients_campaigns_campaign_id");

                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_recipients_prospects_prospect_id");

                    b.Navigation("Campaign");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.Message", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.MessageResponse", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_responses_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Crm.FollowUp", b =>
                {
                    b.HasOne("Hunter.Domain.Crm.Lead", "Lead")
                        .WithMany("FollowUps")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_follow_ups_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Hunter.Domain.Crm.Lead", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leads_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Crm.LeadActivity", b =>
                {
                    b.HasOne("Hunter.Domain.Crm.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_activities_leads_lead_id");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Hunter.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Hunter.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hunter.Domain.Identity.User", b =>
                {
                    b.HasOne("Hunter.Domain.Organizations.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Hunter.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("Hunter.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Hunter.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hunter.Domain.Organizations.OrganizationSettings", b =>
                {
                    b.HasOne("Hunter.Domain.Organizations.Organization", "Organization")
                        .WithMany("Settings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_settings_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ImportBatchRecord", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.ImportBatch", "ImportBatch")
                        .WithMany("Records")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_batch_records_import_batches_import_batch_id");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectContact", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany("Contacts")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prospect_contacts_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectSource", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany("Sources")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prospect_sources_prospects_prospect_id");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ProspectTag", b =>
                {
                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany("ProspectTags")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prospect_tags_prospects_prospect_id");

                    b.HasOne("Hunter.Domain.Prospecting.Tag", "Tag")
                        .WithMany("ProspectTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prospect_tags_tags_tag_id");

                    b.Navigation("Prospect");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Hunter.Domain.Sales.Sale", b =>
                {
                    b.HasOne("Hunter.Domain.Crm.Lead", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_leads_lead_id");

                    b.HasOne("Hunter.Domain.Prospecting.Prospect", "Prospect")
                        .WithMany()
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_prospects_prospect_id");

                    b.Navigation("Lead");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Hunter.Domain.Campaigning.Campaign", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Hunter.Domain.Crm.Lead", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("FollowUps");
                });

            modelBuilder.Entity("Hunter.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hunter.Domain.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Hunter.Domain.Organizations.Organization", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.ImportBatch", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.Prospect", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("ProspectTags");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Hunter.Domain.Prospecting.Tag", b =>
                {
                    b.Navigation("ProspectTags");
                });
#pragma warning restore 612, 618
        }
    }
}
